services:
  app:
    image: jana19/pnpm:24
    volumes:
      - .:/app
    working_dir: /app
    command: 'bash'
    tty: true
    stdin_open: true
    depends_on:
      - adminer
      - redis

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pennywise
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    ports:
      - 3005:8080
    depends_on:
      - db

  redis:
    image: redis:7

volumes:
  db:
  redis:
