export const INVALIDATE_QUERIES_FROM_MUTATION = {
  CREATE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  UPDATE_ACCOUNT_TYPE_NAME: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  UPDATE_ACCOUNT_TYPE_PRIORITY: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  DELETE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  CREATE_ACCOUNT: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_NAME: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_TYPE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_STARTING_DATE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`
  ],
  UPDATE_ACCOUNT_STARTING_BALANCE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`
  ]
}
