export const INVALIDATE_QUERIES_FROM_MUTATION = {
  CREATE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  UPDATE_ACCOUNT_TYPE_NAME: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  UPDATE_ACCOUNT_TYPE_PRIORITY: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  DELETE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  CREATE_ACCOUNT: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_NAME: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_TYPE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  UPDATE_ACCOUNT_STARTING_DATE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`
  ],
  UPDATE_ACCOUNT_STARTING_BALANCE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`
  ],
  DELETE_ACCOUNT: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  CREATE_CATEGORY: [`GET_ALL_CATEGORIES`, `GET_ALL_CATEGORIES_LEAN`],
  UPDATE_CATEGORY_NAME: [`GET_ALL_CATEGORIES`, `GET_ALL_CATEGORIES_LEAN`],
  DELETE_CATEGORY: [`GET_ALL_CATEGORIES`, `GET_ALL_CATEGORIES_LEAN`],
  CREATE_PAYEE: [`GET_ALL_PAYEES`, `GET_ALL_PAYEES_LEAN`],
  UPDATE_PAYEE_NAME: [`GET_ALL_PAYEES`, `GET_ALL_PAYEES_LEAN`],
  DELETE_PAYEE: [`GET_ALL_PAYEES`, `GET_ALL_PAYEES_LEAN`]
}
