export const INVALIDATE_QUERIES_FROM_MUTATION = {
  CREATE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  UPDATE_ACCOUNT_TYPE_NAME: [
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`
  ],
  UPDATE_ACCOUNT_TYPE_PRIORITY: [
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ACCOUNT_BALANCES_REPORT`
  ],
  DELETE_ACCOUNT_TYPE: [`GET_ALL_ACCOUNT_TYPES`, `GET_ALL_ACCOUNT_TYPES_LEAN`],
  CREATE_ACCOUNT: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_ACCOUNT_BALANCES_REPORT`
  ],
  UPDATE_ACCOUNT_NAME: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_ACCOUNT_BALANCES_REPORT`
  ],
  UPDATE_ACCOUNT_TYPE: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`
  ],
  DELETE_ACCOUNT: [
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_ACCOUNTS_LEAN`,
    `GET_ALL_ACCOUNT_TYPES`,
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_ACCOUNT_BALANCES_REPORT`
  ],
  CREATE_CATEGORY: [
    `GET_ALL_CATEGORIES`,
    `GET_ALL_CATEGORIES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`
  ],
  UPDATE_CATEGORY_NAME: [
    `GET_ALL_CATEGORIES`,
    `GET_ALL_CATEGORIES_LEAN`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`
  ],
  DELETE_CATEGORY: [
    `GET_ALL_CATEGORIES`,
    `GET_ALL_CATEGORIES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`
  ],
  CREATE_PAYEE: [
    `GET_ALL_PAYEES`,
    `GET_ALL_PAYEES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  UPDATE_PAYEE_NAME: [
    `GET_ALL_PAYEES`,
    `GET_ALL_PAYEES_LEAN`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  DELETE_PAYEE: [
    `GET_ALL_PAYEES`,
    `GET_ALL_PAYEES_LEAN`,
    `GET_USER_OVERVIEW`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  CREATE_TRANSACTION: [
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_USER_OVERVIEW`,
    `GET_ACCOUNT_BALANCES_REPORT`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  UPDATE_TRANSACTION_DATE: [
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_ACCOUNT_BALANCES_REPORT`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  UPDATE_TRANSACTION_ACCOUNT: [
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_ACCOUNT_BALANCES_REPORT`
  ],
  UPDATE_TRANSACTION_CATEGORY: [
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`
  ],
  UPDATE_TRANSACTION_PAYEE: [
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  UPDATE_TRANSACTION_AMOUNT: [
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_USER_OVERVIEW`,
    `GET_ACCOUNT_BALANCES_REPORT`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ],
  UPDATE_TRANSACTION_MEMO: [`GET_ALL_TRANSACTIONS`],
  DELETE_TRANSACTION: [
    `GET_ALL_ACCOUNT_TYPES_LEAN`,
    `GET_ALL_ACCOUNTS`,
    `GET_ALL_TRANSACTIONS`,
    `GET_ACCOUNT_TRANSACTIONS`,
    `GET_USER_OVERVIEW`,
    `GET_ACCOUNT_BALANCES_REPORT`,
    `GET_EXPENSE_BY_CATEGORY_REPORT`,
    `GET_EXPENSE_BY_PAYEE_REPORT`
  ]
}
